"""self test schedule and progress

Revision ID: 8ed35343cdbb
Revises: a9af5c586342
Create Date: 2026-09-29 04:16:27.766617+00:00

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "8ed35343cdbb"
down_revision = "a9af5c586342"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.add_column(sa.Column("smartd_conf", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("smartd_state", sa.String(length=32), nullable=True))

    with op.batch_alter_table("smart_run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("selftest_hours", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("selftest_progress", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("smart_run", schema=None) as batch_op:
        batch_op.drop_column("selftest_progress")
        batch_op.drop_column("selftest_hours")

    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.drop_column("smartd_state")
        batch_op.drop_column("smartd_conf")

    # ### end Alembic commands ###
