"""push token and attempt transport

Revision ID: fbd948e810f7
Revises: 3a7e164cf5cb
Create Date: 2026-09-29 01:30:24.780475+00:00

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "fbd948e810f7"
down_revision = "3a7e164cf5cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.add_column(sa.Column("push_token_hash", sa.String(length=64), nullable=True))

    with op.batch_alter_table("host_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("transport", sa.String(length=8), nullable=True))
        batch_op.create_index("ix_host_attempt_payload", ["payload_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("host_attempt", schema=None) as batch_op:
        batch_op.drop_index("ix_host_attempt_payload")
        batch_op.drop_column("transport")

    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.drop_column("push_token_hash")

    # ### end Alembic commands ###
