"""initial schema

Revision ID: 3a7e164cf5cb
Revises:
Create Date: 2026-09-28 16:36:41.369025+00:00

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "3a7e164cf5cb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("hosts_expected", sa.Integer(), nullable=False),
        sa.Column("hosts_ok", sa.Integer(), nullable=False),
        sa.Column("hosts_failed", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_key", sa.String(length=128), nullable=False),
        sa.Column("serial_key", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("serial", sa.String(length=128), nullable=True),
        sa.Column("wwn", sa.String(length=32), nullable=True),
        sa.Column("protocol", sa.String(length=16), nullable=True),
        sa.Column("device_type", sa.String(length=32), nullable=True),
        sa.Column("rotation_rate", sa.Integer(), nullable=True),
        sa.Column("capacity_bytes", sa.BigInteger(), nullable=True),
        sa.Column("model_family", sa.String(length=128), nullable=True),
        sa.Column("firmware", sa.String(length=64), nullable=True),
        sa.Column("form_factor", sa.String(length=32), nullable=True),
        sa.Column("identity_source", sa.String(length=16), nullable=False),
        sa.Column("first_seen_at", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=True),
        sa.Column("retired", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_key", "serial_key"),
    )
    op.create_table(
        "host",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("ssh_user", sa.String(length=64), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("tz", sa.String(length=64), nullable=True),
        sa.Column("transport", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("machine_id", sa.String(length=64), nullable=True),
        sa.Column("hostkey", sa.Text(), nullable=True),
        sa.Column("gate_version", sa.Integer(), nullable=True),
        sa.Column("probe_version", sa.Integer(), nullable=True),
        sa.Column("os_release", sa.String(length=128), nullable=True),
        sa.Column("smartctl_version", sa.String(length=64), nullable=True),
        sa.Column("last_success_at", sa.Integer(), nullable=True),
        sa.Column("last_attempt_at", sa.Integer(), nullable=True),
        sa.Column("last_attempt_class", sa.String(length=32), nullable=True),
        sa.Column("last_attempt_reason", sa.Text(), nullable=True),
        sa.Column("unreachable_since", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "attrlog_cursor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("inode", sa.BigInteger(), nullable=True),
        sa.Column("offset", sa.BigInteger(), nullable=False),
        sa.Column("lines", sa.Integer(), nullable=False),
        sa.Column("last_ts", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "file_name"),
    )
    op.create_table(
        "drive_sighting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("drive_id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("dev_name", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drive_id"],
            ["drive.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drive_id", "host_id", "dev_name"),
    )
    op.create_table(
        "host_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("failure_class", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("ssh_rc", sa.Integer(), nullable=True),
        sa.Column("payload_id", sa.String(length=64), nullable=True),
        sa.Column("host_collected_at", sa.Integer(), nullable=True),
        sa.Column("host_tz", sa.String(length=64), nullable=True),
        sa.Column("drives_seen", sa.Integer(), nullable=False),
        sa.Column("bytes_received", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["collection_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("host_attempt", schema=None) as batch_op:
        batch_op.create_index("ix_host_attempt_host_started", ["host_id", "started_at"], unique=False)

    op.create_table(
        "pool",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("first_seen_at", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=True),
        sa.Column("retired", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "kind", "name"),
    )
    op.create_table(
        "pool_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=True),
        sa.Column("collected_at", sa.Integer(), nullable=False),
        sa.Column("health", sa.String(length=32), nullable=True),
        sa.Column("read_errors", sa.Integer(), nullable=True),
        sa.Column("write_errors", sa.Integer(), nullable=True),
        sa.Column("cksum_errors", sa.Integer(), nullable=True),
        sa.Column("scrub", sa.Text(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("verdict", sa.String(length=8), nullable=False),
        sa.Column("reasons", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["host_attempt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["pool.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pool_id", "collected_at"),
    )
    op.create_table(
        "smart_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("drive_id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=True),
        sa.Column("attempt_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("collected_at", sa.Integer(), nullable=False),
        sa.Column("exit_status", sa.Integer(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("standby", sa.Boolean(), nullable=False),
        sa.Column("temp_c", sa.Integer(), nullable=True),
        sa.Column("power_on_hours", sa.Integer(), nullable=True),
        sa.Column("power_cycles", sa.Integer(), nullable=True),
        sa.Column("ata_error_count", sa.Integer(), nullable=True),
        sa.Column("selftest_errors", sa.Integer(), nullable=True),
        sa.Column("selftest_last", sa.String(length=128), nullable=True),
        sa.Column("nvme_percentage_used", sa.Integer(), nullable=True),
        sa.Column("nvme_available_spare", sa.Integer(), nullable=True),
        sa.Column("nvme_spare_threshold", sa.Integer(), nullable=True),
        sa.Column("nvme_media_errors", sa.BigInteger(), nullable=True),
        sa.Column("nvme_critical_warning", sa.Integer(), nullable=True),
        sa.Column("nvme_err_log_entries", sa.BigInteger(), nullable=True),
        sa.Column("nvme_unsafe_shutdowns", sa.BigInteger(), nullable=True),
        sa.Column("nvme_data_units_written", sa.BigInteger(), nullable=True),
        sa.Column("nvme_data_units_read", sa.BigInteger(), nullable=True),
        sa.Column("scsi_grown_defects", sa.Integer(), nullable=True),
        sa.Column("scsi_uncorrected_errors", sa.Integer(), nullable=True),
        sa.Column("messages", sa.Text(), nullable=True),
        sa.Column("raw_json", sa.LargeBinary(), nullable=True),
        sa.Column("verdict", sa.String(length=8), nullable=False),
        sa.Column("reasons", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["host_attempt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["drive_id"],
            ["drive.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drive_id", "source", "collected_at"),
    )
    with op.batch_alter_table("smart_run", schema=None) as batch_op:
        batch_op.create_index("ix_smart_run_drive_time", ["drive_id", "collected_at"], unique=False)

    op.create_table(
        "attr_sample",
        sa.Column("drive_id", sa.Integer(), nullable=False),
        sa.Column("attr_id", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("worst", sa.Integer(), nullable=True),
        sa.Column("thresh", sa.Integer(), nullable=True),
        sa.Column("raw", sa.BigInteger(), nullable=False),
        sa.Column("raw_str", sa.String(length=64), nullable=True),
        sa.Column("when_failed", sa.String(length=8), nullable=True),
        sa.Column("prefail", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["drive_id"],
            ["drive.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["smart_run.id"],
        ),
        sa.PrimaryKeyConstraint("drive_id", "attr_id", "collected_at"),
        sqlite_with_rowid=False,
    )
    with op.batch_alter_table("attr_sample", schema=None) as batch_op:
        batch_op.create_index("ix_attr_sample_run", ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attr_sample", schema=None) as batch_op:
        batch_op.drop_index("ix_attr_sample_run")

    op.drop_table("attr_sample")
    with op.batch_alter_table("smart_run", schema=None) as batch_op:
        batch_op.drop_index("ix_smart_run_drive_time")

    op.drop_table("smart_run")
    op.drop_table("pool_status")
    op.drop_table("pool")
    with op.batch_alter_table("host_attempt", schema=None) as batch_op:
        batch_op.drop_index("ix_host_attempt_host_started")

    op.drop_table("host_attempt")
    op.drop_table("drive_sighting")
    op.drop_table("attrlog_cursor")
    op.drop_table("host")
    op.drop_table("drive")
    op.drop_table("collection_run")
    # ### end Alembic commands ###
