"""host block devices and agent version

Revision ID: 8726e88dfb7c
Revises: fbd948e810f7
Create Date: 2026-09-29 02:56:28.152399+00:00

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "8726e88dfb7c"
down_revision = "fbd948e810f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent_version", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("block_devices", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("host", schema=None) as batch_op:
        batch_op.drop_column("block_devices")
        batch_op.drop_column("agent_version")

    # ### end Alembic commands ###
