"""The pull: ssh to every host in turn (a few at a time), the gate on the other end runs the probe, and
what comes back is ingested one host per transaction so a bad host costs nothing to the others.

Every expected host gets an attempt row per run, with a failure class and the reason when it failed:
unreachable is a fact with a cause on record, never a blank.
"""

from __future__ import annotations

import os
import re
import subprocess
import time
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker

from drivecanary.config import Config
from drivecanary.envelope import Envelope, EnvelopeError, parse_envelope
from drivecanary.ingest import IngestError, IngestResult, ingest_envelope
from drivecanary.logging import get_logger
from drivecanary.models import AttrlogCursor, CollectionRun, FailureClass, Host, HostAttempt, HostState, Transport
from drivecanary.timeutil import hours_ago, utcnow

log = get_logger(__name__)

COLLECT_VERB = "drivecanary-collect"


@dataclass
class SshResult:
    rc: int
    out: bytes
    err: bytes
    timed_out: bool = False
    seconds: float = 0.0


Runner = Callable[[Host, list[str]], SshResult]


def ssh_config_text(cfg: Config, hosts: list[Host]) -> str:
    """The client config the collector runs with: specific hosts first (the first value obtained wins),
    then the defaults. `-F` replaces the system config, so nothing in /etc/ssh leaks in."""
    ssh_dir = cfg.ssh_dir
    lines = ["# generated by drivecanary from the host table; edits are overwritten on the next collection", ""]
    for h in hosts:
        lines += [
            f"Host {h.name}",
            f"    HostName {h.address}",
            f"    Port {h.ssh_port}",
            f"    User {h.ssh_user or cfg.collect.ssh_user}",
            "",
        ]
    lines += [
        "Host *",
        f"    IdentityFile {ssh_dir / 'id_ed25519'}",
        "    IdentitiesOnly yes",
        f"    UserKnownHostsFile {ssh_dir / 'known_hosts'}",
        "    StrictHostKeyChecking yes",
        "    BatchMode yes",
        "    PasswordAuthentication no",
        "    KbdInteractiveAuthentication no",
        f"    ConnectTimeout {cfg.collect.connect_timeout_seconds}",
        "    ServerAliveInterval 15",
        "    ServerAliveCountMax 3",
        "    LogLevel ERROR",
        "",
    ]
    return "\n".join(lines)


def write_ssh_material(cfg: Config, hosts: list[Host]) -> Path:
    """Write the generated config and the pinned known_hosts into [paths].ssh_dir; returns the config path."""
    ssh_dir = cfg.ssh_dir
    ssh_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    config_path = ssh_dir / "config"
    config_path.write_text(ssh_config_text(cfg, hosts))
    known = "\n".join(h.hostkey.strip() for h in hosts if h.hostkey) + "\n"
    (ssh_dir / "known_hosts").write_text(known)
    for p in (config_path, ssh_dir / "known_hosts"):
        os.chmod(p, 0o600)
    return config_path


class SshRunner:
    """Runs the collection verb on one host through the system OpenSSH client."""

    def __init__(self, cfg: Config, config_path: Path) -> None:
        self.cfg = cfg
        self.config_path = config_path

    def __call__(self, host: Host, args: list[str]) -> SshResult:
        cmd = ["ssh", "-F", str(self.config_path), host.name, COLLECT_VERB, *args]
        started = time.monotonic()
        try:
            cp = subprocess.run(cmd, capture_output=True, timeout=self.cfg.collect.host_timeout_seconds, check=False)
        except subprocess.TimeoutExpired as e:
            return SshResult(
                rc=-1, out=e.stdout or b"", err=e.stderr or b"", timed_out=True, seconds=time.monotonic() - started
            )
        except OSError as e:
            return SshResult(rc=-2, out=b"", err=str(e).encode(), seconds=time.monotonic() - started)
        return SshResult(rc=cp.returncode, out=cp.stdout, err=cp.stderr, seconds=time.monotonic() - started)


_UNREACHABLE = re.compile(
    r"timed out|No route to host|Connection refused|Could not resolve|Network is unreachable"
    r"|Name or service not known|Connection reset",
    re.I,
)
_AUTH = re.compile(r"Permission denied|Too many authentication failures|no matching|Unable to negotiate", re.I)
_HOSTKEY = re.compile(
    r"Host key verification failed|HOST IDENTIFICATION HAS CHANGED|host key is known|host key for .* has changed", re.I
)


def classify(result: SshResult, env: Envelope | None, err: Exception | None) -> tuple[FailureClass, str]:
    """Why an attempt failed: the ssh exit status and stderr first, then what the envelope says."""
    stderr = result.err.decode("utf-8", "replace").strip()
    last = stderr.splitlines()[-1] if stderr else ""
    if result.timed_out:
        return FailureClass.TIMEOUT, f"no answer within the host timeout ({last or 'no stderr'})"
    if result.rc == -2:
        return FailureClass.UNKNOWN, f"could not run ssh: {stderr}"
    if result.rc == 255 and env is None:
        if _HOSTKEY.search(stderr):
            return FailureClass.HOSTKEY, last
        if _AUTH.search(stderr):
            return FailureClass.AUTH, last
        if _UNREACHABLE.search(stderr):
            return FailureClass.UNREACHABLE, last
        return FailureClass.UNREACHABLE, last or "ssh exited 255 with no message"
    if result.rc == 127 and env is None:
        return (
            FailureClass.KEY_NOT_RESTRICTED,
            "the remote shell ran the verb as a command: the key is not bound to the gate (command=...)",
        )
    if result.rc == 64 and env is None:
        return FailureClass.ENVELOPE, f"the gate rejected the request: {last}"
    if isinstance(err, IngestError):
        return err.failure_class, err.reason
    if isinstance(err, EnvelopeError):
        return FailureClass.ENVELOPE, str(err)
    if err is not None:
        return FailureClass.UNKNOWN, f"{type(err).__name__}: {err}"
    if result.rc != 0:
        return FailureClass.UNKNOWN, f"ssh exited {result.rc}: {last}"
    return FailureClass.UNKNOWN, "unknown"


def _due(host: Host, cfg: Config, now: datetime) -> bool:
    """Every host every run, except one that has been unreachable for longer than the backoff: that one
    only every retry_every_hours."""
    if host.state != HostState.UNREACHABLE or host.unreachable_since is None:
        return True
    down = hours_ago(host.unreachable_since, now) or 0
    since_try = hours_ago(host.last_attempt_at, now)
    if down < cfg.collect.unreachable_backoff_hours:
        return True
    return since_try is None or since_try >= cfg.collect.retry_every_hours


def _cursor_args(session: Session, host: Host) -> list[str]:
    return [
        f"{c.file_name}={c.offset}"
        for c in session.scalars(select(AttrlogCursor).where(AttrlogCursor.host_id == host.id))
        if c.offset > 0
    ]


@dataclass
class HostOutcome:
    host_id: int
    name: str
    ok: bool
    failure_class: FailureClass | None = None
    reason: str | None = None
    result: IngestResult | None = None


def collect(
    cfg: Config,
    factory: sessionmaker[Session],
    *,
    only: list[str] | None = None,
    runner: Runner | None = None,
    trigger: str = "manual",
    parallel: int | None = None,
) -> tuple[CollectionRun, list[HostOutcome]]:
    now = utcnow()
    with factory() as s:
        hosts = list(s.scalars(select(Host).where(Host.transport == Transport.PULL.value).order_by(Host.name)))
        all_pull = [h for h in hosts if h.state not in (HostState.PAUSED.value, HostState.RETIRED.value)]
        if only:
            missing = set(only) - {h.name for h in hosts}
            if missing:
                raise ValueError(f"unknown host(s): {', '.join(sorted(missing))}")
            wanted = [h for h in hosts if h.name in only]
        else:
            wanted = [h for h in all_pull if _due(h, cfg, now)]
        run = CollectionRun(trigger=trigger, hosts_expected=len(wanted))
        s.add(run)
        attempts: dict[int, HostAttempt] = {}
        args: dict[int, list[str]] = {}
        for h in wanted:
            a = HostAttempt(host_id=h.id, started_at=now)
            s.add(a)
            attempts[h.id] = a
            args[h.id] = _cursor_args(s, h)
            h.last_attempt_at = now
        s.commit()
        run_id = run.id
        attempt_ids = {hid: a.id for hid, a in attempts.items()}
        config_path = write_ssh_material(cfg, hosts)
        s.expunge_all()
    log.info("collect.start", run_id=run_id, hosts=[h.name for h in wanted], trigger=trigger)
    do = runner or SshRunner(cfg, config_path)

    def call(h: Host) -> tuple[Host, SshResult]:
        return h, do(h, args[h.id])

    results: list[tuple[Host, SshResult]] = []
    with ThreadPoolExecutor(max_workers=parallel or cfg.collect.parallel) as pool:
        results = list(pool.map(call, wanted))

    outcomes: list[HostOutcome] = []
    for detached, result in results:
        outcomes.append(_ingest_one(cfg, factory, detached.id, attempt_ids[detached.id], result))
    with factory() as s:
        finished = s.get(CollectionRun, run_id)
        assert finished is not None
        finished.finished_at = utcnow()
        finished.hosts_ok = sum(1 for o in outcomes if o.ok)
        finished.hosts_failed = sum(1 for o in outcomes if not o.ok)
        s.commit()
        s.refresh(finished)
        s.expunge(finished)
    log.info("collect.done", run_id=run_id, ok=finished.hosts_ok, failed=finished.hosts_failed)
    return finished, outcomes


def _ingest_one(
    cfg: Config, factory: sessionmaker[Session], host_id: int, attempt_id: int, result: SshResult
) -> HostOutcome:
    with factory() as s:
        host = s.get(Host, host_id)
        attempt = s.get(HostAttempt, attempt_id)
        assert host is not None and attempt is not None
        attempt.finished_at = utcnow()
        attempt.ssh_rc = result.rc
        attempt.bytes_received = len(result.out)
        env: Envelope | None = None
        error: Exception | None = None
        ingested: IngestResult | None = None
        try:
            if len(result.out) > cfg.collect.max_output_mb * 1024 * 1024:
                raise IngestError(FailureClass.TOO_LARGE, f"envelope of {len(result.out)} bytes exceeds max_output_mb")
            if result.out.startswith(b"DRIVECANARY-ENVELOPE"):
                env = parse_envelope(result.out)
            if env is None or result.timed_out:
                raise IngestError(*classify(result, None, None))
            ingested = ingest_envelope(s, host=host, attempt=attempt, env=env, cfg=cfg)
        except (IngestError, EnvelopeError, ValueError, KeyError) as e:
            error = e
        if error is None and ingested is not None:
            attempt.ok = True
            attempt.drives_seen = ingested.runs
            host.state = HostState.OK.value
            host.last_success_at = attempt.finished_at
            host.last_attempt_class = None
            host.last_attempt_reason = "\n".join(ingested.warnings) or None
            host.unreachable_since = None
            s.commit()
            log.info(
                "collect.host_ok",
                host=host.name,
                runs=ingested.runs,
                pools=ingested.pools,
                attrlog_lines=ingested.attrlog_lines,
                warnings=ingested.warnings,
            )
            return HostOutcome(host_id, host.name, True, result=ingested)
        s.rollback()
        # the rollback undid the attempt bookkeeping too: redo it on fresh objects
        host = s.get(Host, host_id)
        attempt = s.get(HostAttempt, attempt_id)
        assert host is not None and attempt is not None
        fclass, reason = classify(result, env, error)
        attempt.finished_at = utcnow()
        attempt.ssh_rc = result.rc
        attempt.bytes_received = len(result.out)
        attempt.ok = False
        attempt.failure_class = fclass.value
        attempt.reason = reason
        host.last_attempt_class = fclass.value
        host.last_attempt_reason = reason
        if fclass in (FailureClass.UNREACHABLE, FailureClass.TIMEOUT):
            if host.state != HostState.UNREACHABLE.value:
                host.unreachable_since = attempt.finished_at
            host.state = HostState.UNREACHABLE.value
        else:
            host.state = HostState.BROKEN.value
        s.commit()
        log.warning("collect.host_failed", host=host.name, failure_class=fclass.value, reason=reason)
        return HostOutcome(host_id, host.name, False, fclass, reason)
